challenges/challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# app_name = "main" isn't working lol
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('week3/', include('wk3.urls'), name='wk3')
]

challenges/wk3/urls.py
from django.urls import path
from . import views

app_name = "wk3"
urlpatterns = [
    path("", views.index, name="index"),
    path("sussy", views.sussy, name="sussy"),
    path("bob", views.bob, name="bob")
]

challenges/wk3/models.py
from django.db import models

# Create your models here.

challenges/challenges/views.py
from django.shortcuts import render

def index(request):
    return render(request, "challenges/index.html")

challenges/wk3/views.py
# considering that I'm using the same form for both madlibs this is so inefficient

from django.shortcuts import render
from django import forms

class MadLib(forms.Form):
    adj1 = forms.CharField(label="Adjective")
    v1 = forms.CharField(label="Verb (past tense)")
    adj2 = forms.CharField(label="Adjective")
    adj3 = forms.CharField(label="Adjective")
    v2 = forms.CharField(label="Verb (past tense)")

# Create your views here.
def index(request):
    return render(request, "wk3/index.html")

def sussy(request):
    if request.method == "POST":
        form = MadLib(request.POST)
        if form.is_valid():
            results = list(form.clean().values())
            return render(request, "wk3/sussy.html", {
                    "form": form,
                    "result": f"The very {results[0]} impostor vented to medbay. The impostor {results[1]} cyan. Red saw the very {results[2]} do it so red was {results[1]} as well. Thankfully, the {results[3]} player spotted the impostor's shenanigans and the very {results[0]} impostor was {results[4]}."
                })
        else:
            return render(request, "wk3/sussy.html", {
                "form": form
            })
    return render(request, "wk3/sussy.html", {
        "form": MadLib()
    })
def bob(request):
    if request.method == "POST":
        form = MadLib(request.POST)
        if form.is_valid():
            results = list(form.clean().values())
            return render(request, "wk3/bob.html", {
                    "form": form,
                    "result": f"Bob the {results[0]} builder {results[1]} to the farmer's market. He bought some {results[2]} vegetables and {results[3]} fruits. Then he {results[4]} home."
                })
        else:
            return render(request, "wk3/bob.html", {
                "form": form
            })
    return render(request, "wk3/bob.html", {
        "form": MadLib()
    })

challenges/challenges/templates/challenges/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Challenges Home</title>
    </head>
    <body>
        <a href="{% url 'wk3:~~~~~~~' %}">Week 3</a>
    </body>
</html>

challenges/wk3/templates/wk3/bob.html
{% extends 'wk3/layout.html' %}

{% block body %}
    <a href="{% url 'wk3:index' %}">Mainpage</a>
    <h1>Bob</h1>
    <form action="{% url 'wk3:bob' %}" method="post">
        
        {% csrf_token %}
        
        {{ form }}
        <input type="submit">
    </form>
    
    {% if result %}
        <h2>Your result:</h2>
        {{ result }}
    {% endif %}
{% endblock %}

challenges/wk3/templates/wk3/index.html
{% extends "wk3/layout.html" %}

{% block body %}
    <a href="{% url 'index' %}">Homepage</a>
    <h1>Mad Libs</h1>
    <p>Choose a mad lib to do.</p>
    <ul>
        <li><a href="{% url 'wk3:sussy' %}">Sussy</a></li>
        <li><a href="{% url 'wk3:bob' %}">Bob</a></li>
    </ul>
{% endblock %}

challenges/wk3/templates/wk3/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Week 3</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

challenges/wk3/templates/wk3/sussy.html
{% extends 'wk3/layout.html' %}

{% block body %}
    <a href="{% url 'wk3:index' %}">Mainpage</a>
    <h1>Sussy</h1>
    <form action="{% url 'wk3:sussy' %}" method="post">
        
        {% csrf_token %}
        
        {{ form }}
        <input type="submit">
    </form>
    
    {% if result %}
        <h2>Your result:</h2>
        {{ result }}
    {% endif %}
{% endblock %}